lines = $stdin.readlines
cues = []

lines.each do |line|
  line = line.chomp
  if line =~ /^\[@([\d\.]+)\]$/
    cues << { start: $1.to_f, text: [] }
  elsif cues.last
    cues.last[:text] << line.chomp
  end
end

previous = nil
cues.each do |cue|
  previous[:end] = cue[:start] - (4 / 60.0) if previous
  cue[:text] = cue[:text].join("\n").strip
  previous = cue
end

puts "WEBVTT - Generated by https://github.com/dtinth/subtitles"

format_time = ->(t) { "%02d:%02d:%02d.%03d" % [t / 3600, t / 60 % 60, t % 60, (t * 1000) % 1000] }

cues.each do |cue|
  next if cue[:text] == '-'
  puts
  puts "%s --> %s" % [format_time[cue[:start]], format_time[cue[:end]]]
  puts cue[:text]
end
